name: homie
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0
  http: ^0.13.4
  flutter_svg: ^1.1.4
  flutter_spinkit: ^5.1.0
  marquee: ^2.2.0
  animations: ^2.0.2
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.2

  ### Firebase Section
  #Firebase_Initialized
  cloud_firestore: ^3.4.5
  firebase_auth: ^3.6.4
  firebase_storage: ^10.0.3
  firebase_core: ^1.6.0
  file_picker: ^4.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:

  # color: "#42a5f5"
  #background_image: "assets/background.png"
  #image: assets/splash.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  android: ture
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/login/doc.svg
    - asset/profile/profile.webp
    - asset/profile/profile.png
    - asset/search/banner.png
    - asset/signup/bkimg.svg
    - asset/updatepage/updateBanner.svg
    - asset/updatepage/plus.svg
    - asset/updatepage/black.png
    - asset/resetpage/resetBanner.svg
    - asset/medicalreportpage/reportBanner.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: montserrat
      fonts:
        - asset: asset/fonts/montserrat-regular.ttf
          weight: 600
        - asset: asset/fonts/montserrat-semibold.ttf
          weight: 700
    
    - family: orbitron
      fonts:
        - asset: asset/fonts/orbitron.ttf
          weight: 400
    
    - family: awesome
      fonts:
        - asset: asset/fonts/fontawesome6regular.ttf
          weight: 400
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
