name: homie
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0
  http: ^0.13.4
  flutter_svg: ^1.1.4
  flutter_spinkit: ^5.1.0
  animations: ^2.0.2
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  syncfusion_flutter_pdf: ^20.2.46
  open_file: ^3.2.1
  fl_chart: ^0.55.2
  percent_indicator: ^4.2.2
  tflite_flutter: ^0.9.0
  flutter_close_app: ^1.0.0

  ### Firebase Section
  #Firebase_Initialized
  cloud_firestore: ^3.4.5
  firebase_auth: ^3.6.4
  firebase_storage: ^10.0.3
  firebase_core: ^1.6.0
  file_picker: ^4.0.3
  google_maps_flutter: ^2.1.12
  shared_preferences: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:

  # color: "#42a5f5"
  #background_image: "assets/background.png"
  #image: assets/splash.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  android: ture
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/login/doc.svg
    - asset/profile/profile.webp
    - asset/profile/profile.png
    - asset/search/banner.png
    - asset/signup/bkimg.svg
    - asset/updatepage/updateBanner.svg
    - asset/updatepage/plus.svg
    - asset/updatepage/black.png
    - asset/resetpage/resetBanner.svg
    - asset/medicalreportpage/reportBanner.svg
    - asset/dailyReport/emoji.png
    - asset/homepage/airticle1.png
    - asset/homepage/airticle2.png
    - asset/homepage/airticle3.png
    - asset/homepage/airticle4.png
    - asset/homepage/airticle5.png

  fonts:
    - family: montserrat
      fonts:
        - asset: asset/fonts/montserrat-regular.ttf
          weight: 600
        - asset: asset/fonts/montserrat-semibold.ttf
          weight: 700
    
    - family: orbitron
      fonts:
        - asset: asset/fonts/orbitron.ttf
          weight: 400
    
    - family: awesome
      fonts:
        - asset: asset/fonts/fontawesome6regular.ttf
          weight: 400
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
